version: '3.8'
services:
  db:
    container_name: toro-db
    image: mysql:9
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql